Config = Config or {}

Config.HasSpawned = false

Config.Spawn = {['X'] = -59.18, ['Y'] = -1109.71, ['Z'] = 25.45, ['H'] = 68.5}
Config.Sell = {['X'] = -44.60, ['Y'] = -1081.41, ['Z'] = 26.69}

Config.Vehicles = {
  [1] = {
    ['Coords'] = {['X'] = -45.65, ['Y'] = -1093.66, ['Z'] = 25.44, ['H'] = 69.5},
    ['current-vehicle'] = 's',
    ['Busy'] = false,
  },
  [2] = {
    ['Coords'] = {['X'] = -48.27, ['Y'] = -1101.86, ['Z'] = 25.44, ['H'] = 294.5},
    ['current-vehicle'] = 's',
    ['Busy'] = false, 
  },
  [3] = {
    ['Coords'] = {['X'] = -40.39, ['Y'] = -1095.13, ['Z'] = 25.44, ['H'] = 205.82},
    ['current-vehicle'] = 's',
    ['Busy'] = false,
  },
  [4] = {
    ['Coords'] = {['X'] = -40.18, ['Y'] = -1104.13, ['Z'] = 25.44, ['H'] = 338.5},
    ['current-vehicle'] = 's',
    ['Busy'] = false,
  },
  [5] = {
    ['Coords'] = {['X'] = -36.21, ['Y'] = -1097.74, ['Z'] = 26.42, ['H'] = 112.64},
    ['current-vehicle'] = 's',
    ['Busy'] = false,
  },
  [6] = {
    ['Coords'] = {['X'] = -50.66, ['Y'] = -1093.05, ['Z'] = 25.44, ['H'] = 222.5},
    ['current-vehicle'] = 's',
    ['Busy'] = false,
  },
}

Config.VehicleClasses = {
-- // Sports \ --
['schafter3'] = {['Price'] = 67000,    ['Name'] = 'Benefactor Schafter V12'},
['sultan'] = {['Price'] = 50000,       ['Name'] = 'Karin Sultan'},
['sultanrs'] = {['Price'] = 70000,     ['Name'] = 'Karin SultanRS'},
['elegy'] = {['Price'] = 63000,        ['Name'] = 'Annis Elegy'},
['carbonizzare'] = {['Price'] = 80000, ['Name'] = 'Grotti Carbonzzare'},
['comet3'] = {['Price'] = 112000,      ['Name'] = 'Pfister Comet Sports'},
['jester'] = {['Price'] = 125000,      ['Name'] = 'Dinka Jester'},
['stinger'] = {['Price'] = 135000,      ['Name'] = 'Grotti Stinger'},
['adder'] = {['Price'] = 650000,      ['Name'] = 'Truffade Adder'},
-- // Sedans \ --
['premier'] = {['Price'] = 12500,  ['Name'] = 'Declasse Premier'},
['primo2'] = {['Price'] = 22500,   ['Name'] = 'Albany Primo'},
['superd'] = {['Price'] = 125000,  ['Name'] = 'Enus Super Diamond'},
['stafford'] = {['Price'] = 30000, ['Name'] = 'Enus Stafford'},
['glendale'] = {['Price'] = 14500, ['Name'] = 'Benefactor Glendale'},
['intruder'] = {['Price'] = 15000, ['Name'] = 'Karin Intruder'},
['emperor2'] = {['Price'] = 7500,  ['Name'] = 'Albany Emperor'},
['weevil'] = {['Price'] = 31500,  ['Name'] = 'BF Weevil'},
['brioso2'] = {['Price'] = 29500,  ['Name'] = 'Grotti Brioso'},
-- // Motors \ --
['akuma'] = {['Price'] = 21500,    ['Name'] = 'Dinka Akuma'},
['bati'] = {['Price'] = 22500,     ['Name'] = 'Pegassi Bati'},
['bagger'] = {['Price'] = 9750,    ['Name'] = 'Western Bagger'},
['bf400'] = {['Price'] = 15500,    ['Name'] = 'Nagasaki BF400'},
['carbonrs'] = {['Price'] = 20000, ['Name'] = 'Nagasaki CarbonRS'},
['double'] = {['Price'] = 19750,   ['Name'] = 'Dinka Double'},
['faggio'] = {['Price'] = 2000,    ['Name'] = 'Pegassi Faggio'},
['manchez2'] = {['Price'] = 27500,    ['Name'] = 'Maibatsu Manchez'},
-- // Muscle \ --
['buccaneer2'] = {['Price'] = 23000, ['Name'] = 'Albany Buccaneer'},
['dominator'] = {['Price'] = 21000,  ['Name'] = 'Vapid Dominator'},
['chino'] = {['Price'] = 22500,      ['Name'] = 'Vapid Chino'},
['dukes'] = {['Price'] = 18500,      ['Name'] = 'Imponte Dukes'},
['faction2'] = {['Price'] = 23750,   ['Name'] = 'Willard Faction'},
['moonbeam2'] = {['Price'] = 27950,  ['Name'] = 'Declasse Moonbeam'},
['btype'] = {['Price'] = 82500,  ['Name'] = 'Albany Roosevelt'},
['btype2'] = {['Price'] = 125000,  ['Name'] = 'Albany Franken Strange'},
['btype3'] = {['Price'] = 95000,  ['Name'] = 'Albany Roosevelt Valor'},
['manana'] = {['Price'] = 25500,  ['Name'] = 'Albany Manana'},
-- // Vans \ --
['bison'] = {['Price'] = 23000, ['Name'] = 'Bravado Bison'},
['minivan'] = {['Price'] = 25400,  ['Name'] = 'Vapid Minivan'},
['bobcatxl'] = {['Price'] = 26970,      ['Name'] = 'Vapid Bobcat XL'},
['youga'] = {['Price'] = 21500,      ['Name'] = 'Bravado Youga'},
['sandking'] = {['Price'] = 23750,   ['Name'] = 'Vapid Sandking'},
['toros'] = {['Price'] = 90000,  ['Name'] = 'Pegassi Toros'},
['winky'] = {['Price'] = 25750,  ['Name'] = 'Vapid Winky'},
['dubsta'] = {['Price'] = 145000,  ['Name'] = 'Benefactor Dubsta'},
-- // Addon \ --
['m2'] = {['Price'] = 125000,     ['Name'] = 'BMW M2'},
['x5e53'] = {['Price'] = 85000,   ['Name'] = 'BMW X5'},
['cls63s'] = {['Price'] = 200000, ['Name'] = 'Mercedes CLS63'},
['911turbos'] = {['Price'] = 175000, ['Name'] = 'Porsche 911'},
['16challenger'] = {['Price'] = 200000, ['Name'] = 'Dodge Challenger'},
['bmci'] = {['Price'] = 250000, ['Name'] = 'BMW M5 F90'},
['skyline'] = {['Price'] = 120000, ['Name'] = 'Nissan R34 Skyline'},
['rapide'] = {['Price'] = 320000, ['Name'] = 'Aston Martin Rapide'},
['audirs6tk'] = {['Price'] = 285000, ['Name'] = 'Audi RS6 C7'},
['a45amg'] = {['Price'] = 90000, ['Name'] = 'Mercedes-Benz A45 AMG'},
['g632019'] = {['Price'] = 350000, ['Name'] = 'Mercedes-Benz G63 AMG'},
['rrab'] = {['Price'] = 380000, ['Name'] = 'Range Rover Autobiography Mansory'},
['pstmansory'] = {['Price'] = 230000, ['Name'] = 'Porsche Panamera Turbo S Mansory'},
['golf7gti'] = {['Price'] = 85000, ['Name'] = 'Volkswagen Golf MK7 GTI'},
['brabus850'] = {['Price'] = 245000, ['Name'] = 'Brabus 850'},
}

Config.RandomVehicles = {
    ['sport'] = {
      [1] = 'schafter3',
      [2] = 'sultan',
      [3] = 'sultanrs',
      [4] = 'elegy',
      [5] = 'carbonizzare',
      [6] = 'comet3',
      [7] = 'jester',
      [8] = 'stinger',
      [9] = 'adder',
    },
    ['sedan'] = {
      [1] = 'premier',
      [2] = 'primo2',
      [3] = 'superd',
      [4] = 'stafford',
      [5] = 'glendale',
      [6] = 'intruder',
      [7] = 'emperor2',
      [8] = 'weevil',
      [9] = 'brioso2',
    },
    ['motors'] = {
      [1] = 'akuma',
      [2] = 'bati',
      [3] = 'bagger',
      [4] = 'bf400',
      [5] = 'carbonrs',
      [6] = 'double',
      [7] = 'faggio',
      [8] = 'manchez2',
    },
    ['muscle'] = {
      [1] = 'buccaneer2',
      [2] = 'dominator',
      [3] = 'chino',
      [4] = 'dukes',
      [5] = 'faction2',
      [6] = 'moonbeam2',
      [7] = 'btype',
      [8] = 'btype2',
      [9] = 'btype3',
      [10] = 'manana',
    },
    ['vans'] = {
      [1] = 'bison',
      [2] = 'minivan',
      [3] = 'bobcatxl',
      [4] = 'youga',
      [5] = 'sandking',
      [6] = 'toros',
      [7] = 'winky',
      [8] = 'dubsta',
    },
    ['addon'] = {
      [1] = 'm2',
      [2] = 'x5e53',
      [3] = '911turbos',
      [4] = 'cls63s',
      [5] = '16challenger',
      [6] = 'skyline',
      [7] = 'rapide',
      [8] = 'bmci',
      [9] = 'audirs6tk',
      [10] = 'a45amg',
      [11] = 'g632019',
      [12] = 'pstmansory',
      [13] = 'rrab',
      [14] = 'golf7gti',
    },
}